### ISSUE TITLE
[ISSUE] Fix CRON Job in Documentation

### ISSUE THREAD

**Issue by adamgourley** [libellux/Libellux-Up-and-Running#100]
At [this](https://www.libellux.com/openvas/#scheduled-jobs) section, it says the path for the greenbone-feed-sync is /usr/local/bin/greenbone-feed-sync, but on Ubuntu 20.04, it is in /usr/local/**sbin**/greenbone-feed-sync.

Could be a mistype in the doc, or am I missing something here?

**Comment by libellux** [comment]
Thanks will test it amend the changes for the coming revision. Added to the road map.
