### ISSUE TITLE
GVM Rev. 9

### ISSUE THREAD

**Issue by libellux** [libellux/Libellux-Up-and-Running#126]
GVM revision 9 to include installation of GVM 22.4.0 on Ubuntu 22.04.

**Comment by machadommm** [comment]
Hi,
I think that have a problem:

# Set version, Download and verify GVMD
export GVMD_VERSION=22.4 && \
curl -f -L https://github.com/greenbone/gvmd/archive/refs/tags/v$GVMD_VERSION.tar.gz -o $SOURCE_DIR/gvmd-$GVMD_VERSION.tar.gz && \
curl -f -L https://github.com/greenbone/gvmd/releases/download/v$GVMD_VERSION/gvmd-$GVMD_VERSION.tar.gz.asc -o $SOURCE_DIR/gvmd-$GVMD_VERSION.tar.gz.asc && \
gpg --verify $SOURCE_DIR/gvmd-$GVMD_VERSION.tar.gz.asc $SOURCE_DIR/gvmd-$GVMD_VERSION.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1014k    0 1014k    0     0  1731k      0 --:--:-- --:--:-- --:--:-- 1731k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

Could you check this?

**Comment by libellux** [comment]
Hello @machadommm you missed the 0:

export GVMD_VERSION=22.4.0

Im still having issues on ubuntu 22.04 tho. You can follow the thread here: https://community.greenbone.net/t/install-gvm-21-4-2-ubuntu-20-04/10057/54
