### ISSUE TITLE
Problem to start gvmd in script ubuntu_22.4.0.sh

### ISSUE THREAD

**Issue by machadommm** [libellux/Libellux-Up-and-Running#132]
Hi,
I followed the script for installation but it is giving an error to start the gmvd service.

Below the captured log:

root@openvas:~ tail -n 20 /var/log/gvm/gvmd.log
md manage:WARNING:2022-08-02 12h38.00 utc:20526: sql_exec_internal: SQL: SELECT value FROM public.meta WHERE name = 'database_version';
md manage:WARNING:2022-08-02 12h38.00 utc:20526: sql_x: sql_exec_internal failed
md manage:MESSAGE:2022-08-02 12h38.00 utc:20526: No SCAP database found
md manage:MESSAGE:2022-08-02 12h38.00 utc:20526: No CERT database found
md manage:MESSAGE:2022-08-02 12h38.00 utc:20526: db_extension_available: Extension 'pg-gvm' is not available.
md manage:WARNING:2022-08-02 12h38.00 utc:20526: check_db_extensions: A required extension is not available.
md manage:WARNING:2022-08-02 12h38.00 utc:20526: init_manage_create_functions: failed to create functions
md   main:MESSAGE:2022-08-02 12h39.31 utc:20536:    Greenbone Vulnerability Manager version 22.4.0~dev1 (DB revision 250)
md manage:WARNING:2022-08-02 12h39.31 utc:20537: sql_exec_internal: PQexec failed: ERROR:  relation "public.meta" does not exist
LINE 1: SELECT value FROM public.meta WHERE name = 'database_version...
md manage:WARNING:2022-08-02 12h39.31 utc:20537: sql_exec_internal: SQL: SELECT value FROM public.meta WHERE name = 'database_version';
md manage:WARNING:2022-08-02 12h39.31 utc:20537: sql_x: sql_exec_internal failed
md manage:MESSAGE:2022-08-02 12h39.31 utc:20537: No SCAP database found
md manage:MESSAGE:2022-08-02 12h39.31 utc:20537: No CERT database found
md manage:MESSAGE:2022-08-02 12h39.31 utc:20537: db_extension_available: Extension 'pg-gvm' is not available.
md manage:WARNING:2022-08-02 12h39.31 utc:20537: check_db_extensions: A required extension is not available.
md manage:WARNING:2022-08-02 12h39.31 utc:20537: init_manage_create_functions: failed to create functions

Any tips?

**Comment by libellux** [comment]
Hello @machadommm reading the error logs you've shared it seems like the new postegreSQL helper/wrapper isn't correctly installed. This is new for the 22.4.0 release, make sure that you've installed that helper correctly. I've been running through my script 3 times already on a fresh Ubuntu 22.04 vm without any issues.

**Comment by machadommm** [comment]
Hi,
I re-installed my virtual machine from scratch.
Now your installation script worked correctly. Well done!!
Thank you very much for your excellent work.
Cheers,
Mauro

**Comment by libellux** [comment]
No worries and thank you for the kind words! happy you got it to work!
