### ISSUE TITLE
Certain Files no longer available 

### ISSUE THREAD

**Issue by engr-mayz** [libellux/Libellux-Up-and-Running#135]
**Describe the bug**
A  404 error is received when certain files is been accessed.

https://github.com/greenbone/gvm-libs/archive/refs/tags/v$GVM_LIBS_VERSION.tar.gz 
https://github.com/greenbone/gvm-libs/releases/download/v$GVM_LIBS_VERSION/gvm-libs-$GVM_LIBS_VERSION.tar.gz.asc 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu]
 - Version [e.g. 20.04]

**Additional context**
Inability to download the files severely limits the planned installation

**Comment by libellux** [comment]
Thanks @engr-mayz will have a look at it tomorrow.

**Comment by libellux** [comment]
This will be all resolved tomorrow with my latest update. Got all to work this evening.
