### ISSUE TITLE
[BUG] ubuntu-22_04_GVM-22.4.0.sh contains errors

### ISSUE THREAD

**Issue by Foxi352** [libellux/Libellux-Up-and-Running#141]
**Environment:**
 - OS: Ubuntu
 - Version 22.04.2 LTS

**Describe the bug**
On a fresh minimal install of `Ubuntu 22.04.2 LTS running script `ubuntu-22_04_GVM-22.4.0.sh` as root use from root home directory.

First it ends for me being in `visudo` editor. After i exit `vi` the script ends with:

```
visudo: /etc/sudoers.tmp unchanged
./ubuntu-22_04_GVM-22.4.0.sh: line 286: syntax error near unexpected token `('
./ubuntu-22_04_GVM-22.4.0.sh: line 286: `%sudo   ALL=(ALL:ALL) ALL'
```
After commenting out the lines, doing the `visudo` part manually and relaunching the script i end up in a bash prompt as `postgres` user:
```
postgres@ubuntu:/root/source/notus-scanner-22.4.0$
```
After i `exit` from the shell back into `root` shell the script ends with:
```
createuser: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
createdb: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist
./ubuntu-22_04_GVM-22.4.0.sh: line 300: create: command not found
./ubuntu-22_04_GVM-22.4.0.sh: line 301: grant: command not found
./ubuntu-22_04_GVM-22.4.0.sh: line 302: create: command not found
./ubuntu-22_04_GVM-22.4.0.sh: line 303: create: command not found
```

I stopped there for now because of time constraints. I am sure this will get fixed, and  i want to thank you for your hard work on this one.

**Comment by sergeymeleschenko** [comment]
Got the same error

**Comment by megabitus98** [comment]
I've hit the same issue, and I've tried to change the script a bit. Here is the edited script that worked for me. [ubuntu-22_04_GVM-22.4.1.sh](https://gist.github.com/megabitus98/c94bb02e13ef9f6061fdb29e0dcc6133).
For some reason the first time running the script it stops after doing the lines with apt. I just neded to run it again, and ran with no issues.

**Comment by libellux** [comment]
Hello @sergeymeleschenko & @megabitus98 keep in mind that the bash files aren't really "scripts" but rather files I use when I do testing/updating my website. The "scripts" should be considered as line by line commands you'd use. I'm more than happy tho if you want to take your time to rework them to actual executeables.
