### ISSUE TITLE
Report Format must be active

### ISSUE THREAD

**Issue by xsidkaosx** [libellux/Libellux-Up-and-Running#29]
Hi guys.  @libellux 
Perform the GVM 20.08 installation, but when trying to open the reports tab, it shows the following message:

![Screenshot_20210205_172329](https://user-images.githubusercontent.com/36538362/107096431-c3c50d00-67d8-11eb-86ee-6b81094f3ebb.png)

 - OS: Ubuntu
 - Version: 20.04

I try run so to get all the syncs up-to-date: 

/opt/gvm/sbin/greenbone-feed-sync --type GVMD_DATA
/opt/gvm/sbin/greenbone-feed-sync --type SCAP
/opt/gvm/sbin/greenbone-feed-sync --type CERT

I can see the report formats tab, it shows the following list: 

![image](https://user-images.githubusercontent.com/36538362/107096727-5fef1400-67d9-11eb-9f6b-efa93befe42a.png)

The log error report does not show any connection errors: 
gsad.log  gvmd.log  openvas.log  ospd-openvas.log

i can see in Console Log: 
![image](https://user-images.githubusercontent.com/36538362/107097352-c45ea300-67da-11eb-8afa-5e24ff6cbaa0.png)

`  <envelope><version>20.08.1~git-fc9e55140-gsa-20.08</version><vendor_version></vendor_version><token>9145c23c-4f71-48e4-be9f-973a1e22bee2</token><time>Fri Feb  5 22:45:39 2021 UTC</time><login>gvmadmin</login><role>Admin</role><i18n>es_ES</i18n><client_address>192.168.0.133</client_address><gsad_response><title>Error: get_entities:999 (GSA 20.08.1~git-fc9e55140-gsa-20.08)</title><message>Report format must be active</message></gsad_response><capabilities><help_response status="200" status_text="OK">`

Best regards,
Joseph

**Comment by libellux** [comment]
@xsidkaosx I will take a look tomorrow (sorry for the late reply) and try to reproduce the error and see if I can find a fix.

**Comment by libellux** [comment]
@xsidkaosx please see https://github.com/libellux/Libellux-Up-and-Running/issues/18#issuecomment-781551511
