### ISSUE TITLE
openvas/config/21_4_2.sh error 

### ISSUE THREAD

**Issue by johndoeisavailable** [libellux/Libellux-Up-and-Running#50]
Hi, thank you for the installation instructions, but I there is a small problem with one of the commands.

After calling:

`sudo /usr/local/sbin/gvmd --create-user=admin --password=admin`

this error appears:

`/usr/local/sbin/gvmd: error while loading shared libraries: libgvm_base.so.21: cannot open shared object file: No such file or directory`

Do you know how to resolve it?

**Comment by johndoeisavailable** [comment]
Running `ldconfig` helped

**Comment by libellux** [comment]
Thanks for letting me know @johndoeisavailable will add and make sure its clear.
