### ISSUE TITLE
LOG nmap issue with openvas scanner

### ISSUE THREAD

**Issue by TatusGepetto** [libellux/Libellux-Up-and-Running#73]
Hi,
There is a problem inside scanner results, related to nmap scanner. I have just a log message with warning:
WARNING: You requested the Nmap scan type -PE (ICMP echo probe) which requires root privileges but scanner is running under an unprivileged user. Nmap has used TCP ping scan instead, if you want use -PE start the scanner as root.
![obraz](https://user-images.githubusercontent.com/20689412/144042725-73fa47f1-53d0-4ba2-93c4-c45bfa1cda01.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**
I was following installation instructions from here: https://www.libellux.com/openvas -> Everything is well described, however I couldn't find a way how to solve this issue, especially that nmap command is working fine when executed as:
sudo -u gvm nmap ...

Sudoers file is configured the same way as inside tutorial. I'm just wondering what kind of hack is needed here. Thanks in advance for you input.

**Comment by libellux** [comment]
Hello @TatusGepetto so I just installed a fresh source build from my guide. Unfortuntely I do not get the same log message as you. I get the results for both "SSH Server type and version" with other port and protocol scans when I ran vulnerability check against a test host intrusion detection server (ossec) for example:

```
2021 Dec 22 04:13:40 localhost->/var/log/secure
Rule: 5701 (level 8) -> 'Possible attack on the ssh server (or version gathering).'
Dec 22 04:13:39 localhost sshd[13923]: error: Protocol major versions differ: 2 vs. 1
```

If you want to probe your external host make sure that your target host default firewall doesn't block the port scanner - as explained here: https://explainshell.com/explain?cmd=nmap+-PE

I hope you'll resolve it and that I've been to some help at least.

**Comment by TatusGepetto** [comment]
Hello @libellux , thank you very much for your answer. I made another approach and change recognition option to "Consider alive", as I'm fully sure that such IPs and ports are responsive:
![obraz](https://user-images.githubusercontent.com/20689412/148192899-286421ae-be40-4132-8081-6478e811ec0e.png)

But it didn't change too much, Of course I don't see this problem with nmap execution, but I can see only LOG responses, no other issues(which would be fine IF my system is fully bulletproof):
![obraz](https://user-images.githubusercontent.com/20689412/148193657-0022f2ca-4540-4b0f-9e72-97630fba5a54.png)


But if I will compare it to one of the last scans from operational 20.08 system, I was able to get there:
![obraz](https://user-images.githubusercontent.com/20689412/148193612-f7183e32-1cf4-41ce-b753-b96ef909bc4c.png)

I know that for this example host I still should be able to get LOW and MEDIUM alerts about:
![obraz](https://user-images.githubusercontent.com/20689412/148193795-fd13184f-6e0b-43b9-bb73-1f8d709916f0.png)
![obraz](https://user-images.githubusercontent.com/20689412/148193835-3747bbc2-ca07-45c5-8c61-e8138d5d1eec.png)

As I didn't fix it, but it seems that newer version of system doesn't provide such response. So I'm wondering if installation method is somehow corrupted or something else is wrong.

I added additionally such options to sudoers file:
```
# allow users of the gvm group run nmap and arping
%gvm ALL = NOPASSWD: /usr/bin/nmap
%gvm ALL = NOPASSWD: /usr/sbin/arping
```

But it didn't change anything.

So I'm wondering if you have any advices, cause it seems that my system is somehow partially OK.

**Comment by TatusGepetto** [comment]
Finally after reinstallation from scratch it seems it works. Maybe something was wrong with sources during time of my installation, as it didn't provide any error messages when installed. 

Anyway, I believe we can simply close it.
