### ISSUE TITLE
[BUG] missing steps, incorrect commands in cron job feed update GVM

### ISSUE THREAD

**Issue by innertruth** [libellux/Libellux-Up-and-Running#99]
**Describe the bug**
location: https://www.libellux.com/openvas/#scheduled-jobs, the Ubuntu parts
see also: https://community.greenbone.net/t/problem-with-update-cron-job-on-gsa-21-4-3/12098

I can confirm the OP is saying, tested OP's solution and added some things.

This: (the greenbone-feed-sync is found in sbin, not bin, will result in not performing greenbone-feed-sync)
```
/usr/local/bin/greenbone-nvt-sync
/usr/local/bin/greenbone-feed-sync --type GVMD_DATA
/usr/local/bin/greenbone-feed-sync --type SCAP
/usr/local/bin/greenbone-feed-sync --type CERT
```
Suggested changes:
```
/usr/local/bin/greenbone-nvt-sync
/usr/local/sbin/greenbone-feed-sync --type GVMD_DATA
/usr/local/sbin/greenbone-feed-sync --type SCAP
/usr/local/sbin/greenbone-feed-sync --type CERT
```

And this, missing step how to get to root:
Edit the root crontab and add the file you created to check for daily updates.
`server@ubuntu:~$ crontab -e`
Suggested changes:
Edit the root crontab and add the file you created to check for daily updates.
`server@ubuntu:~$ sudo su`
[enter password]
`root@ubuntu:~$ crontab -e`

And this:
`0 0 * * * gvm /usr/local/bin/openvas-update`
(this will result in error that gvm command could not be found)
Suggested changes:
`0 0 * * * sudo -u gvm /usr/local/bin/openvas-update`

Suggested addition at the end:
While in root, test your update of the feed:
(while in root user):
`root@ubuntu:~$ sudo -u gvm /usr/local/bin/openvas-update`

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04
 - GVM: GVM 21.4.5

**Comment by libellux** [comment]
Thanks @innertruth will update documentation on next revision. Added to road map.
